// SPDX-License-Identifier: MIT
#pragma once

#include <string>

namespace Sleeve::FileWriter {

enum class FileVerdict {
  New,          // File does not exist yet
  Managed,      // File exists and was generated by sleeve (matches record hash)
  HandEdited,   // File exists, has sleeve marker, but was modified since last generation
  Foreign,      // File exists and has no sleeve marker (unsafe to overwrite)
};

struct FileStatus {
  std::string path;
  FileVerdict verdict {FileVerdict::New};
  std::string disk_sha256;
  std::string existing_content;
};

// Check the status of a file against expected sleeve markers and recorded sha256
FileStatus CheckStatus(const std::string& path, const std::string& recordedSha256 = "");

// Calculate SHA-256 hex string of a string or file
std::string ComputeSha256(const std::string& content);
std::string ComputeFileSha256(const std::string& path);

// Atomically write content to file with specified mode (e.g. 0755 or 0644)
bool AtomicWrite(const std::string& path, const std::string& content, mode_t mode = 0644);

// Backup foreign file to <path>.pre-sleeve
bool MoveAside(const std::string& path);

} // namespace Sleeve::FileWriter
