// SPDX-License-Identifier: MIT
#include "Generate.h"
#include "Paths.h"
#include "Shapes.h"
#include "ElfInspect.h"
#include "AppConfigWriter.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <regex>

namespace Sleeve::Generate {

namespace fs = std::filesystem;

static std::string ShellEscapePath(const std::string& path) {
  std::string p = Paths::ContractUser(path);
  if (p.rfind("~/", 0) == 0) {
    return "$HOME" + p.substr(1);
  }
  return p;
}

GeneratedOutputs GenerateFiles(const Record::AppRecord& r) {
  GeneratedOutputs out;

  const char* home = std::getenv("HOME");
  std::string homeStr = home ? home : "";

  out.launcher_path = homeStr + "/.local/bin/" + r.name;

  std::ostringstream ss;
  ss << "#!/bin/sh\n";
  ss << "# generated by sleeve  record=~/.config/powerarm/sleeve/apps/" << r.name << ".json  -- edit the record, not this\n";
  ss << "# " << r.title << " (arm64) under POWERarm. Regenerate with: sleeve wrap " << r.name << "\n";

  if (!r.rootfs.empty()) {
    ss << "export POWERARM_ROOTFS=\"${POWERARM_ROOTFS:-" << ShellEscapePath(r.rootfs) << "}\"\n";
  }

  if (r.emulator.has_value() && !r.emulator->empty()) {
    ss << "export POWERARM_PORTABLE=1\n";
  }

  if (r.mangohud.enabled) {
    ss << "export MANGOHUD=1\n";
    ss << "export LD_PRELOAD='/usr/$LIB/mangohud/libMangoHud_shim.so'\n";
    ss << "export MANGOHUD_CONFIG=\"${MANGOHUD_CONFIG:-" << r.mangohud.config << "}\"\n";
    ss << "export POWERARM_PROFILESTATS=1\n";
  }

  for (const auto& [k, v] : r.env) {
    ss << "export " << k << "=\"${" << k << ":-" << v << "}\"\n";
  }

  std::string exePath = r.GetResolvedExePath();
  std::string exeEscaped = ShellEscapePath(exePath);

  if (r.cwd == "install" && !r.source.dir.empty()) {
    ss << "cd \"" << ShellEscapePath(r.source.dir) << "\" && ";
  }

  ss << "exec ";
  if (r.emulator.has_value() && !r.emulator->empty()) {
    ss << "\"" << ShellEscapePath(*r.emulator) << "\" \"" << exeEscaped << "\"";
  } else {
    ss << "\"" << exeEscaped << "\"";
  }

  for (const auto& arg : r.args) {
    ss << " " << arg;
  }
  ss << " \"$@\"\n";

  out.launcher_content = ss.str();

  if (r.desktop.enabled) {
    out.has_desktop = true;
    out.desktop_path = homeStr + "/.local/share/applications/" + r.name + "-arm64.desktop";

    std::ostringstream dss;
    dss << "[Desktop Entry]\n";
    dss << "Type=Application\n";
    dss << "Name=" << (r.desktop.name.empty() ? r.title + " (arm64)" : r.desktop.name) << "\n";
    dss << "Comment=" << (r.desktop.comment.empty() ? r.title + " under POWERarm" : r.desktop.comment) << "\n";
    dss << "Exec=" << out.launcher_path << " " << (r.desktop.exec_field.empty() ? "%F" : r.desktop.exec_field) << "\n";

    std::string iconPath = r.GetResolvedIconPath();
    if (!iconPath.empty()) {
      dss << "Icon=" << Paths::ExpandUser(iconPath) << "\n";
    }

    if (!r.desktop.categories.empty()) {
      dss << "Categories=" << r.desktop.categories << "\n";
    }
    if (!r.desktop.wmclass.empty()) {
      dss << "StartupWMClass=" << r.desktop.wmclass << "\n";
    }
    if (!r.desktop.mimetypes.empty()) {
      dss << "MimeType=" << r.desktop.mimetypes << "\n";
    }

    dss << "X-Sleeve-Managed=true\n";
    dss << "X-Sleeve-Record=" << Paths::ExpandUser(Paths::GetRecordDir() + "/" + r.name + ".json") << "\n";

    out.desktop_content = dss.str();
  }

  out.has_appconfig = true;
  out.appconfig_path = Paths::GetAppConfigDir() + "/" + r.name + ".json";
  std::string existingAppConfig;
  std::ifstream acIn(out.appconfig_path);
  if (acIn.is_open()) {
    std::stringstream acss;
    acss << acIn.rdbuf();
    existingAppConfig = acss.str();
  }
  out.appconfig_content = AppConfigWriter::GenerateAppConfigContent(r, existingAppConfig);

  return out;
}

std::optional<Record::AppRecord> ImportForeignLauncher(const std::string& launcherPath, const std::string& defaultName) {
  std::ifstream f(launcherPath);
  if (!f.is_open()) return std::nullopt;

  std::string name = defaultName;
  if (name.empty()) {
    name = fs::path(launcherPath).filename().string();
  }

  std::string line;
  std::string rootfs;
  std::map<std::string, std::string> env;
  std::string execLine;
  std::string cdDir;

  while (std::getline(f, line)) {
    while (!line.empty() && (line.back() == '\r' || line.back() == ' ')) line.pop_back();
    if (line.empty() || line[0] == '#') continue;

    if (line.rfind("export POWERARM_ROOTFS=", 0) == 0) {
      std::string val = line.substr(23);
      if (val.rfind("\"${POWERARM_ROOTFS:-", 0) == 0) {
        val = val.substr(20);
        if (val.size() >= 2 && val.substr(val.size() - 2) == "}\"") {
          val = val.substr(0, val.size() - 2);
        }
      } else if (val.size() >= 2 && val.front() == '"' && val.back() == '"') {
        val = val.substr(1, val.size() - 2);
      }
      rootfs = Paths::ExpandUser(val);
    } else if (line.rfind("export ", 0) == 0) {
      std::string rest = line.substr(7);
      auto eq = rest.find('=');
      if (eq != std::string::npos) {
        std::string k = rest.substr(0, eq);
        std::string v = rest.substr(eq + 1);
        if (v.rfind("\"${" + k + ":-", 0) == 0) {
          v = v.substr(5 + k.size());
          if (v.size() >= 2 && v.substr(v.size() - 2) == "}\"") {
            v = v.substr(0, v.size() - 2);
          }
        } else if (v.size() >= 2 && v.front() == '"' && v.back() == '"') {
          v = v.substr(1, v.size() - 2);
        }
        if (k != "POWERARM_PORTABLE" && k != "MANGOHUD" && k != "LD_PRELOAD" && k != "POWERARM_PROFILESTATS") {
          env[k] = v;
        }
      }
    } else if (line.find("cd ") != std::string::npos && line.find("&&") != std::string::npos) {
      size_t cdPos = line.find("cd ");
      size_t ampPos = line.find("&&", cdPos);
      std::string dir = line.substr(cdPos + 3, ampPos - (cdPos + 3));
      while (!dir.empty() && dir.back() == ' ') dir.pop_back();
      if (dir.size() >= 2 && dir.front() == '"' && dir.back() == '"') {
        dir = dir.substr(1, dir.size() - 2);
      }
      cdDir = Paths::ExpandUser(dir);
      if (line.find("exec ", ampPos) != std::string::npos) {
        execLine = line.substr(line.find("exec ", ampPos) + 5);
      }
    } else if (line.rfind("exec ", 0) == 0) {
      execLine = line.substr(5);
    }
  }

  if (execLine.empty()) return std::nullopt;

  // Parse execLine into exe and args
  std::string targetExe;
  std::vector<std::string> args;

  std::istringstream xstream(execLine);
  std::string token;
  bool inExe = true;

  while (xstream >> token) {
    if (token.size() >= 2 && token.front() == '"' && token.back() == '"') {
      token = token.substr(1, token.size() - 2);
    }
    if (inExe) {
      targetExe = Paths::ExpandUser(token);
      inExe = false;
    } else {
      if (token == "\"$@\"" || token == "$@") {
        continue;
      }
      args.push_back(token);
    }
  }

  if (targetExe.empty()) return std::nullopt;

  // If targetExe references $POWERARM_ROOTFS
  if (!rootfs.empty()) {
    if (targetExe.rfind("${POWERARM_ROOTFS}", 0) == 0) {
      targetExe = rootfs + targetExe.substr(18);
    } else if (targetExe.rfind("$POWERARM_ROOTFS", 0) == 0) {
      targetExe = rootfs + targetExe.substr(16);
    }
  }

  if (!cdDir.empty() && targetExe.rfind("./", 0) == 0) {
    targetExe = cdDir + "/" + targetExe.substr(2);
  }

  // Inspect targetExe or underlying ELF
  std::string elfProbeTarget = targetExe;
  auto probe = ElfInspect::ProbeFile(elfProbeTarget);

  if (probe.kind != ElfInspect::FileKind::AArch64_Exec && probe.kind != ElfInspect::FileKind::AArch64_Dyn) {
    // Check if it's in a /bin/ directory and an ELF exists in parent
    fs::path p(targetExe);
    if (p.parent_path().filename() == "bin") {
      std::string siblingElf = (p.parent_path().parent_path() / p.filename()).string();
      auto siblingProbe = ElfInspect::ProbeFile(siblingElf);
      if (siblingProbe.kind == ElfInspect::FileKind::AArch64_Exec || siblingProbe.kind == ElfInspect::FileKind::AArch64_Dyn) {
        elfProbeTarget = siblingElf;
        probe = siblingProbe;
      }
    }
  }

  if (probe.kind != ElfInspect::FileKind::AArch64_Exec && probe.kind != ElfInspect::FileKind::AArch64_Dyn) {
    return std::nullopt;
  }

  std::string parentDir = fs::path(elfProbeTarget).parent_path().string();
  if (fs::path(parentDir).filename() == "bin") {
    parentDir = fs::path(parentDir).parent_path().string();
  } else if (fs::path(parentDir).filename() == "arm64" && fs::path(parentDir).parent_path().filename() == "bin") {
    parentDir = fs::path(parentDir).parent_path().parent_path().string();
  }

  auto cand = Shapes::DetectDirectoryShape(parentDir, {elfProbeTarget});
  if (!cand) {
    auto details = ElfInspect::InspectAArch64(elfProbeTarget);
    if (details) {
      cand = Shapes::DetectBinaryShape(elfProbeTarget, *details);
    }
  }

  Shapes::AppCandidate c;
  if (cand) {
    c = *cand;
  } else {
    c.name = name;
    c.title = name;
    c.exe_path = targetExe;
  }

  c.name = name;
  if (!rootfs.empty()) c.rootfs_base = rootfs;
  if (!cdDir.empty()) c.cwd = "install";
  c.default_args = args;
  for (const auto& [k, v] : env) {
    c.default_env[k] = v;
  }

  return Record::CreateFromCandidate(c, rootfs);
}

} // namespace Sleeve::Generate
