// SPDX-License-Identifier: MIT
#include "Generate.h"
#include "Paths.h"
#include "Shapes.h"
#include "ElfInspect.h"
#include "AppConfigWriter.h"
#include "Backend.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <regex>

namespace Sleeve::Generate {

namespace fs = std::filesystem;

// Escapes the characters that end a double-quoted sh word. `$` is deliberately left
// alone: records store paths and arguments that are meant to expand ($HOME), and the
// generator's whole job is to put them inside quotes so the expansion cannot word-split.
static std::string EscapeForDoubleQuotes(const std::string& value) {
  std::string out;
  out.reserve(value.size() + 8);
  for (char c : value) {
    if (c == '"' || c == '\\' || c == '`') {
      out.push_back('\\');
    }
    out.push_back(c);
  }
  return out;
}

// The body of a double-quoted word for a path: ~/x becomes $HOME/x so the launcher stays
// portable between machines. Callers put the quotes on (directly, or around a larger word).
static std::string ShellPathBody(const std::string& path) {
  std::string p = Paths::ContractUser(path);
  if (p.rfind("~/", 0) == 0) {
    return "$HOME" + EscapeForDoubleQuotes(p.substr(1));
  }
  return EscapeForDoubleQuotes(p);
}

// A complete, quoted sh word for a path.
static std::string ShellQuotePath(const std::string& path) {
  return "\"" + ShellPathBody(path) + "\"";
}

// A complete sh word for a record argument. Left bare when every character is inert,
// quoted otherwise -- including whenever the argument expands something, because the
// expansion is what would word-split on a path with a space in it.
static std::string ShellQuoteArg(const std::string& arg) {
  // Records written by older versions carry their own quotes; strip one wrapping pair
  // so the app does not receive literal quote characters in argv.
  std::string value = arg;
  if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
    value = value.substr(1, value.size() - 2);
  }

  if (value.empty()) return "\"\"";

  bool inert = true;
  for (char c : value) {
    bool safe = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') ||
                c == '-' || c == '_' || c == '.' || c == '/' || c == ':' || c == ',' ||
                c == '=' || c == '+' || c == '@' || c == '%';
    if (!safe) {
      inert = false;
      break;
    }
  }
  if (inert) return value;

  return "\"" + EscapeForDoubleQuotes(value) + "\"";
}

// Desktop entry Exec= is a command line, not a path: a program path containing a space
// has to be quoted there too, or the launcher splits it into program plus argument.
static std::string DesktopExecQuote(const std::string& path) {
  if (path.find_first_of(" \t\"\\'><~|&;$*?#()`") == std::string::npos) {
    return path;
  }
  std::string out = "\"";
  for (char c : path) {
    if (c == '"' || c == '\\' || c == '`' || c == '$') out.push_back('\\');
    out.push_back(c);
  }
  out.push_back('"');
  return out;
}

GeneratedOutputs GenerateFiles(const Record::AppRecord& r) {
  GeneratedOutputs out;

  const char* home = std::getenv("HOME");
  std::string homeStr = home ? home : "";

  out.launcher_path = homeStr + "/.local/bin/" + r.name;

  const auto& backend = Backend::GetActiveBackend();

  std::ostringstream ss;
  ss << "#!/bin/sh\n";
  ss << "# generated by sleeve  record=~/.config/" << backend.configSubdir << "/sleeve/apps/" << r.name << ".json  -- edit the record, not this\n";
  ss << "# " << r.title << " (" << backend.archName << ") under " << backend.displayName << ". Regenerate with: sleeve wrap " << r.name << "\n";

  if (!r.rootfs.empty()) {
    ss << "export " << backend.envPrefix << "ROOTFS=\"${" << backend.envPrefix << "ROOTFS:-" << ShellPathBody(r.rootfs) << "}\"\n";
  }

  if (r.emulator.has_value() && !r.emulator->empty()) {
    ss << "export " << backend.envPrefix << "PORTABLE=1\n";
  }

  if (r.mangohud.enabled) {
    ss << "export MANGOHUD=1\n";
    ss << "export LD_PRELOAD='/usr/$LIB/mangohud/libMangoHud_shim.so'\n";
    ss << "export MANGOHUD_CONFIG=\"${MANGOHUD_CONFIG:-" << EscapeForDoubleQuotes(r.mangohud.config) << "}\"\n";
    ss << "export " << backend.envPrefix << "PROFILESTATS=1\n";
  }

  for (const auto& [k, v] : r.env) {
    ss << "export " << k << "=\"${" << k << ":-" << EscapeForDoubleQuotes(v) << "}\"\n";
  }

  std::string exePath = r.GetResolvedExePath();
  std::string exeQuoted = ShellQuotePath(exePath);

  if (r.cwd == "install" && !r.source.dir.empty()) {
    ss << "cd " << ShellQuotePath(r.source.dir) << " && ";
  }

  ss << "exec ";
  if (r.emulator.has_value() && !r.emulator->empty()) {
    ss << ShellQuotePath(*r.emulator) << " " << exeQuoted;
  } else {
    ss << exeQuoted;
  }

  for (const auto& arg : r.args) {
    ss << " " << ShellQuoteArg(arg);
  }
  ss << " \"$@\"\n";

  out.launcher_content = ss.str();

  if (r.desktop.enabled) {
    out.has_desktop = true;
    out.desktop_path = homeStr + "/.local/share/applications/" + r.name + "-" + backend.archName + ".desktop";

    std::ostringstream dss;
    dss << "[Desktop Entry]\n";
    dss << "Type=Application\n";
    // No shape here can finish a startup notification: the launcher hands off to a wrapper
    // script, then to the emulator, and the guest toolkit's window app_id does not match
    // StartupWMClass -- so the desktop's launch indicator would spin until it timed out.
    dss << "StartupNotify=" << (r.desktop.startup_notify ? "true" : "false") << "\n";
    dss << "Name=" << (r.desktop.name.empty() ? r.title + " (" + backend.archName + ")" : r.desktop.name) << "\n";
    dss << "Comment=" << (r.desktop.comment.empty() ? r.title + " under " + backend.displayName : r.desktop.comment) << "\n";
    dss << "Exec=" << DesktopExecQuote(out.launcher_path) << " " << (r.desktop.exec_field.empty() ? "%F" : r.desktop.exec_field) << "\n";

    std::string iconPath = r.GetResolvedIconPath();
    if (!iconPath.empty()) {
      dss << "Icon=" << Paths::ExpandUser(iconPath) << "\n";
    }

    if (!r.desktop.categories.empty()) {
      dss << "Categories=" << r.desktop.categories << "\n";
    }
    if (!r.desktop.wmclass.empty()) {
      dss << "StartupWMClass=" << r.desktop.wmclass << "\n";
    }
    if (!r.desktop.mimetypes.empty()) {
      dss << "MimeType=" << r.desktop.mimetypes << "\n";
    }

    dss << "X-Sleeve-Managed=true\n";
    dss << "X-Sleeve-Record=" << Paths::ExpandUser(Paths::GetRecordDir() + "/" + r.name + ".json") << "\n";

    out.desktop_content = dss.str();
  }

  out.has_appconfig = true;
  out.appconfig_path = Paths::GetAppConfigDir() + "/" + r.name + ".json";
  std::string existingAppConfig;
  std::ifstream acIn(out.appconfig_path);
  if (acIn.is_open()) {
    std::stringstream acss;
    acss << acIn.rdbuf();
    existingAppConfig = acss.str();
  }
  out.appconfig_content = AppConfigWriter::GenerateAppConfigContent(r, existingAppConfig);

  return out;
}

std::optional<Record::AppRecord> ImportForeignLauncher(const std::string& launcherPath, const std::string& defaultName) {
  std::ifstream f(launcherPath);
  if (!f.is_open()) return std::nullopt;

  std::string name = defaultName;
  if (name.empty()) {
    name = fs::path(launcherPath).filename().string();
  }

  const auto& backend = Backend::GetActiveBackend();
  const std::string rootfsVar = backend.envPrefix + "ROOTFS";
  const std::string rootfsExport = "export " + rootfsVar + "=";

  std::string line;
  std::string rootfs;
  std::map<std::string, std::string> env;
  std::string execLine;
  std::string cdDir;

  while (std::getline(f, line)) {
    while (!line.empty() && (line.back() == '\r' || line.back() == ' ')) line.pop_back();
    if (line.empty() || line[0] == '#') continue;

    if (line.rfind(rootfsExport, 0) == 0) {
      std::string val = line.substr(rootfsExport.size());
      std::string indirect = "\"${" + rootfsVar + ":-";
      if (val.rfind(indirect, 0) == 0) {
        val = val.substr(indirect.size());
        if (val.size() >= 2 && val.substr(val.size() - 2) == "}\"") {
          val = val.substr(0, val.size() - 2);
        }
      } else if (val.size() >= 2 && val.front() == '"' && val.back() == '"') {
        val = val.substr(1, val.size() - 2);
      }
      rootfs = Paths::ExpandUser(val);
    } else if (line.rfind("export ", 0) == 0) {
      std::string rest = line.substr(7);
      auto eq = rest.find('=');
      if (eq != std::string::npos) {
        std::string k = rest.substr(0, eq);
        std::string v = rest.substr(eq + 1);
        if (v.rfind("\"${" + k + ":-", 0) == 0) {
          v = v.substr(5 + k.size());
          if (v.size() >= 2 && v.substr(v.size() - 2) == "}\"") {
            v = v.substr(0, v.size() - 2);
          }
        } else if (v.size() >= 2 && v.front() == '"' && v.back() == '"') {
          v = v.substr(1, v.size() - 2);
        }
        if (k != backend.envPrefix + "PORTABLE" && k != "MANGOHUD" && k != "LD_PRELOAD" &&
            k != backend.envPrefix + "PROFILESTATS") {
          env[k] = v;
        }
      }
    } else if (line.find("cd ") != std::string::npos && line.find("&&") != std::string::npos) {
      size_t cdPos = line.find("cd ");
      size_t ampPos = line.find("&&", cdPos);
      std::string dir = line.substr(cdPos + 3, ampPos - (cdPos + 3));
      while (!dir.empty() && dir.back() == ' ') dir.pop_back();
      if (dir.size() >= 2 && dir.front() == '"' && dir.back() == '"') {
        dir = dir.substr(1, dir.size() - 2);
      }
      cdDir = Paths::ExpandUser(dir);
      if (line.find("exec ", ampPos) != std::string::npos) {
        execLine = line.substr(line.find("exec ", ampPos) + 5);
      }
    } else if (line.rfind("exec ", 0) == 0) {
      execLine = line.substr(5);
    }
  }

  if (execLine.empty()) return std::nullopt;

  // Parse execLine into exe and args
  std::string targetExe;
  std::vector<std::string> args;

  std::istringstream xstream(execLine);
  std::string token;
  bool inExe = true;

  while (xstream >> token) {
    if (token.size() >= 2 && token.front() == '"' && token.back() == '"') {
      token = token.substr(1, token.size() - 2);
    }
    if (inExe) {
      targetExe = Paths::ExpandUser(token);
      inExe = false;
    } else {
      if (token == "\"$@\"" || token == "$@") {
        continue;
      }
      args.push_back(token);
    }
  }

  if (targetExe.empty()) return std::nullopt;

  // If targetExe references the backend's ROOTFS variable
  if (!rootfs.empty()) {
    std::string braced = "${" + rootfsVar + "}";
    std::string bare = "$" + rootfsVar;
    if (targetExe.rfind(braced, 0) == 0) {
      targetExe = rootfs + targetExe.substr(braced.size());
    } else if (targetExe.rfind(bare, 0) == 0) {
      targetExe = rootfs + targetExe.substr(bare.size());
    }
  }

  if (!cdDir.empty() && targetExe.rfind("./", 0) == 0) {
    targetExe = cdDir + "/" + targetExe.substr(2);
  }

  // Inspect targetExe or underlying ELF
  std::string elfProbeTarget = targetExe;
  auto probe = ElfInspect::ProbeFile(elfProbeTarget);

  if (!ElfInspect::IsTargetBinary(probe)) {
    // Check if it's in a /bin/ directory and an ELF exists in parent
    fs::path p(targetExe);
    if (p.parent_path().filename() == "bin") {
      std::string siblingElf = (p.parent_path().parent_path() / p.filename()).string();
      auto siblingProbe = ElfInspect::ProbeFile(siblingElf);
      if (ElfInspect::IsTargetBinary(siblingProbe)) {
        elfProbeTarget = siblingElf;
        probe = siblingProbe;
      }
    }
  }

  if (!ElfInspect::IsTargetBinary(probe)) {
    return std::nullopt;
  }

  std::string parentDir = fs::path(elfProbeTarget).parent_path().string();
  if (fs::path(parentDir).filename() == "bin") {
    parentDir = fs::path(parentDir).parent_path().string();
  } else if (fs::path(parentDir).filename() == "arm64" && fs::path(parentDir).parent_path().filename() == "bin") {
    parentDir = fs::path(parentDir).parent_path().parent_path().string();
  }

  auto cand = Shapes::DetectDirectoryShape(parentDir, {elfProbeTarget});
  if (!cand) {
    auto details = ElfInspect::InspectTarget(elfProbeTarget);
    if (details) {
      cand = Shapes::DetectBinaryShape(elfProbeTarget, *details);
    }
  }

  Shapes::AppCandidate c;
  if (cand) {
    c = *cand;
  } else {
    c.name = name;
    c.title = name;
    c.exe_path = targetExe;
  }

  c.name = name;
  if (!rootfs.empty()) c.rootfs_base = rootfs;
  if (!cdDir.empty()) c.cwd = "install";
  c.default_args = args;
  for (const auto& [k, v] : env) {
    c.default_env[k] = v;
  }

  return Record::CreateFromCandidate(c, rootfs);
}

} // namespace Sleeve::Generate
