// SPDX-License-Identifier: MIT
#include <catch2/catch_test_macros.hpp>
#include "Generate.h"
#include "Record.h"
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;
using namespace Sleeve;

TEST_CASE("Generate: Golden launcher and desktop entry", "[sleeve][generate]") {
  Record::AppRecord r;
  r.name = "code";
  r.title = "Visual Studio Code";
  r.shape = "electron";
  r.source.kind = "dir";
  r.source.dir = "/home/jbettcher/Development/vscode-arm64";
  r.exe = "current/bin/code";
  r.args = {"--no-sandbox"};
  r.env["ELECTRON_OZONE_PLATFORM_HINT"] = "auto";
  r.rootfs = "/home/jbettcher/.local/share/powerarm/RootFS/ArchLinuxARM-vk";
  r.desktop.enabled = true;
  r.desktop.name = "Visual Studio Code (arm64)";
  r.desktop.wmclass = "Code";
  r.desktop.icon = "current/resources/app/resources/linux/code.png";
  r.desktop.categories = "Development;IDE;TextEditor;";

  auto out = Generate::GenerateFiles(r);

  // Verify launcher
  CHECK(out.launcher_content.find("#!/bin/sh") != std::string::npos);
  CHECK(out.launcher_content.find("# generated by sleeve") != std::string::npos);
  CHECK(out.launcher_content.find("export POWERARM_ROOTFS=\"${POWERARM_ROOTFS:-$HOME/.local/share/powerarm/RootFS/ArchLinuxARM-vk}\"") != std::string::npos);
  CHECK(out.launcher_content.find("export ELECTRON_OZONE_PLATFORM_HINT=\"${ELECTRON_OZONE_PLATFORM_HINT:-auto}\"") != std::string::npos);
  CHECK(out.launcher_content.find("exec \"$HOME/Development/vscode-arm64/current/bin/code\" --no-sandbox \"$@\"") != std::string::npos);

  // Verify desktop entry
  REQUIRE(out.has_desktop);
  CHECK(out.desktop_content.find("[Desktop Entry]") != std::string::npos);
  CHECK(out.desktop_content.find("Name=Visual Studio Code (arm64)") != std::string::npos);
  CHECK(out.desktop_content.find("StartupWMClass=Code") != std::string::npos);
  CHECK(out.desktop_content.find("X-Sleeve-Managed=true") != std::string::npos);
}
