// SPDX-License-Identifier: MIT
#include <catch2/catch_test_macros.hpp>
#include "FileWriter.h"
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;
using namespace Sleeve::FileWriter;

TEST_CASE("FileWriter: Ownership verdicts and atomic write", "[sleeve][filewriter]") {
  std::string tmpDir = "/tmp/sleeve_test_fw";
  fs::create_directories(tmpDir);

  std::string path = tmpDir + "/test_script.sh";

  // 1. Non-existent file -> New
  {
    auto st = CheckStatus(path);
    CHECK(st.verdict == FileVerdict::New);
  }

  // 2. Write managed file
  std::string content = "#!/bin/sh\n# generated by sleeve\necho hello\n";
  REQUIRE(AtomicWrite(path, content, 0755));

  std::string sha = ComputeSha256(content);
  {
    auto st = CheckStatus(path, sha);
    CHECK(st.verdict == FileVerdict::Managed);
  }

  // 3. Hand-edited file (marker present, hash differs)
  {
    auto st = CheckStatus(path, "sha256:different");
    CHECK(st.verdict == FileVerdict::HandEdited);
  }

  // 4. Foreign file (no marker)
  std::string foreignPath = tmpDir + "/foreign.sh";
  std::string foreignContent = "#!/bin/sh\necho foreign\n";
  REQUIRE(AtomicWrite(foreignPath, foreignContent, 0755));

  {
    auto st = CheckStatus(foreignPath);
    CHECK(st.verdict == FileVerdict::Foreign);
  }

  // 5. MoveAside
  REQUIRE(MoveAside(foreignPath));
  CHECK(!fs::exists(foreignPath));
  CHECK(fs::exists(foreignPath + ".pre-sleeve"));

  fs::remove_all(tmpDir);
}

TEST_CASE("FileWriter: SHA-256 computation", "[sleeve][sha256]") {
  // Known standard test vector: empty string
  // sha256("") = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  std::string emptySha = ComputeSha256("");
  CHECK(emptySha == "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");

  // "hello\n"
  std::string helloSha = ComputeSha256("hello\n");
  CHECK(helloSha == "sha256:5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03");
}
